#!/usr/bin/env python3
"""
Refresh the real airframes and callsigns that static/js/demo.js uses.

    python3 tools/build_demo_data.py        # downloads two public datasets, rewrites the FLEET and ROUTES blocks in demo.js

The demo's movements are simulated, but what it shows about each flight is real:
  * FLEET:  real airframes (registration + ICAO hex that belong together, right type, right owner), so the
            browser can ask Planespotters for a photo by hex, exactly as the live dashboard does.
            Source: tar1090-db, https://github.com/wiedehopf/tar1090-db (CSV branch).
  * ROUTES: real callsigns for the routes the demo flies, with the flight number they are sold as.
            Source: Virtual Radar Server standing data (CC0), https://github.com/vradarserver/standing-data,
            the same data server.py uses for routes.
Standard library only, Python 3.5+.
"""
import csv
import gzip
import io
import json
import os
import re
import sys
import urllib.request
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
DEMO = os.path.join(ROOT, "static", "js", "demo.js")
URL = "https://raw.githubusercontent.com/wiedehopf/tar1090-db/csv/aircraft.csv.gz"
SD_URL = "https://codeload.github.com/vradarserver/standing-data/zip/refs/heads/main"
BLOCKS = {"FLEET": ("/* FLEET:BEGIN (generated by tools/build_demo_data.py) */", "/* FLEET:END */"),
          "ROUTES": ("/* ROUTES:BEGIN (generated by tools/build_demo_data.py) */", "/* ROUTES:END */")}

# operator code -> start of the registered owner's name in the database
OWNERS = {
    "UAL": "UNITED AIRLINES", "DAL": "DELTA AIR LINES", "AAL": "AMERICAN AIRLINES", "ASA": "ALASKA AIRLINES INC", "SWA": "SOUTHWEST AIRLINES",
    "JBU": "JETBLUE AIRWAYS", "HAL": "HAWAIIAN AIRLINES", "SKW": "SKYWEST AIRLINES", "QXE": "HORIZON AIR INDUSTRIES", "FDX": "FEDERAL EXPRESS",
    "UPS": "UNITED PARCEL SERVICE", "EJA": "NETJETS SALES", "WJA": "WESTJET", "ACA": "AIR CANADA",
}
# (operator, type) -> how many different airframes the demo needs (a few spare are added)
NEED = {
    ("UAL", "B738"): 16, ("UAL", "A319"): 2, ("UAL", "A320"): 3, ("UAL", "A21N"): 5, ("UAL", "B38M"): 3, ("UAL", "B39M"): 6, ("UAL", "B753"): 3, ("UAL", "B789"): 11,
    ("DAL", "B738"): 2, ("DAL", "B739"): 2, ("DAL", "B752"): 2, ("DAL", "A321"): 15, ("DAL", "A359"): 9,
    ("AAL", "A321"): 7, ("AAL", "A21N"): 11, ("ASA", "B739"): 15, ("ASA", "B738"): 3, ("ASA", "B39M"): 2,
    ("SWA", "B38M"): 21, ("SWA", "B738"): 2, ("JBU", "A321"): 2, ("HAL", "A21N"): 2,
    ("SKW", "E75L"): 8, ("SKW", "CRJ9"): 4, ("QXE", "E75L"): 4,
    ("FDX", "MD11"): 3, ("UPS", "B744"): 2, ("EJA", "CL35"): 3, ("WJA", "B38M"): 2, ("ACA", "A320"): 3, ("ACA", "B38M"): 9,
}
NEED[("DAL", "A321")] += 1                                         # DAL from JFK replaces a Delta A350 the routes data has no flight for
# long-haul visitors whose owner isn't in the database under a simple name: operator, type -> registrations to look up
NAMED = {("ANZ", "B789"): ["ZK-NZQ"], ("BAW", "A388"): ["G-XLEA", "G-XLEB", "G-XLEC"], ("ANA", "B788"): ["JA874A"]}

# callsign prefix -> two-letter code its flights are sold under
IATA = {"UAL": "UA", "DAL": "DL", "AAL": "AA", "ASA": "AS", "SWA": "WN", "JBU": "B6", "HAL": "HA", "ACA": "AC", "WJA": "WS",
        "ANZ": "NZ", "ANA": "NH", "BAW": "BA", "FDX": "FX", "UPS": "5X"}
# Who a regional flight is sold as. Horizon flies only for Alaska, under the same number. SkyWest flies for several airlines and
# its callsign numbers are not the numbers the flights are sold under, so SkyWest flights are shown under SkyWest alone.
REGIONALS = {"QXE": ["ASA"], "SKW": []}
ALWAYS_SOLD_AS = {"QXE": "AS"}                                   # every Horizon flight is an Alaska flight with the same number
# Some airlines broadcast a code instead of the flight number, and the routes data lists both, so they are given here.
CALLSIGN_OF = {"BAW": {("LHR", "SFO"): [("BAW5L", "BA285")]}}
BAY = {"SFO", "OAK", "SJC"}
WEST = ["LAX", "SEA", "SAN", "PDX", "YVR", "PHX", "LAS"]          # the far-away cruisers fly between these
OTHER = [("ANC", "MEM"), ("ANC", "SDF")]
PER_PAIR = 8


def block(src, name, js):
    begin, end = BLOCKS[name]
    new, k = re.subn(re.escape(begin) + r".*?" + re.escape(end), lambda m: "{}\n  {}\n  {}".format(begin, js, end), src, flags=re.S)
    if k != 1:
        sys.exit("build_demo_data: couldn't find the {} block in demo.js".format(name))
    return new


def build_routes(cities):
    print("downloading " + SD_URL)
    z = zipfile.ZipFile(io.BytesIO(urllib.request.urlopen(SD_URL, timeout=180).read()))
    icao2iata, lat = {}, {}
    for n in z.namelist():
        if "/airports/schema-01/" in n and n.endswith(".csv"):
            for r in csv.DictReader(io.TextIOWrapper(z.open(n), encoding="utf-8-sig")):
                if r["IATA"] and r["ICAO"]:
                    icao2iata[r["ICAO"]] = r["IATA"]
                    lat[r["IATA"]] = float(r["Latitude"] or 0)

    def legs(op):
        name = [n for n in z.namelist() if n.endswith("/routes/schema-01/{}/{}-all.csv".format(op[0], op))]
        out = {}
        for n in name:
            for r in csv.DictReader(io.TextIOWrapper(z.open(n), encoding="utf-8-sig")):
                ap = [icao2iata.get(x, "?") for x in r["AirportCodes"].split("-")]
                out[r["Callsign"]] = (r["Number"], set(zip(ap, ap[1:])))
        return out

    ops = sorted(set(OWNERS) | {"ANZ", "ANA", "BAW"})
    data = {op: legs(op) for op in set(ops) | {p for v in REGIONALS.values() for p in v}}
    routes, far = {}, {}
    for op in ops:
        for cs, (num, segs) in sorted(data[op].items(), key=lambda kv: (len(kv[0]), kv[0])):
            if not re.match(r"^[A-Z]{3}\d{1,4}$", cs):                  # only flight-number callsigns: their flight number is certain
                continue
            n = cs[3:]
            if op in REGIONALS:
                sold = next((IATA[p] + n for p in REGIONALS[op] if p + n in data[p] and data[p][p + n][1] & segs), "")
                sold = sold or (ALWAYS_SOLD_AS[op] + n if op in ALWAYS_SOLD_AS else "")
                if not sold and REGIONALS[op]:
                    continue                                          # don't guess who a regional flight is sold as
            else:
                sold = IATA.get(op, "") + n if op in IATA else ""
            for o, d in sorted(segs):
                if o == d:
                    continue
                if ((o in BAY and d in cities) or (d in BAY and o in cities) or (o in WEST and d in WEST) or (o, d) in OTHER) and op not in CALLSIGN_OF:
                    routes.setdefault(op, {}).setdefault(o + "-" + d, [])
                    if len(routes[op][o + "-" + d]) < PER_PAIR:
                        routes[op][o + "-" + d].append([cs, sold])
                if o in WEST and d in WEST:
                    k = "north" if lat.get(d, 0) > lat.get(o, 0) else "south"
                    lst = far.setdefault(op, {}).setdefault(k, [])
                    if sum(1 for e in lst if e[1:3] == [o, d]) < 4 and len(lst) < 40:
                        lst.append([cs, o, d, sold])
    for op, pairs in CALLSIGN_OF.items():
        for (o, d), lst in pairs.items():
            routes.setdefault(op, {})[o + "-" + d] = [[c, s] for c, s in lst]
    return routes, far


def main():
    print("downloading " + URL)
    raw = gzip.decompress(urllib.request.urlopen(URL, timeout=120).read()).decode("utf-8", "replace")
    rows = [l.split(";") for l in raw.splitlines()]
    rows = [r for r in rows if len(r) > 6 and r[1] and r[2]]
    by_reg = {r[1]: r for r in rows}
    fleet, taken = {}, set()
    for (op, typ), n in sorted(NEED.items()):
        pool = sorted((r for r in rows if r[2] == typ and r[6].upper().startswith(OWNERS[op]) and "MISCODE" not in r[6].upper() and "," not in r[6] and re.match(r"^[NC]-?[A-Z0-9]{3,5}$", r[1])), key=lambda r: r[0])
        pool = [r for r in pool if r[0] not in taken]
        want = n + 3
        if len(pool) < n:
            sys.exit("not enough {} {} in the database: need {}, found {}".format(op, typ, n, len(pool)))
        step = max(1, len(pool) // want)
        pick = pool[::step][:want]
        taken.update(r[0] for r in pick)
        fleet.setdefault(op, {})[typ] = [[r[1], r[0]] for r in pick]
    for (op, typ), regs in NAMED.items():
        for reg in regs:
            r = by_reg.get(reg)
            if not r or r[2] != typ:
                sys.exit("{} is not a {} in the database (got {})".format(reg, typ, r and r[2]))
            fleet.setdefault(op, {}).setdefault(typ, []).append([r[1], r[0]])
    with open(DEMO, encoding="utf-8") as f:
        src = f.read()
    cities = set(re.findall(r"\b([A-Z]{3}): '", src.split("const CITIES")[1].split("};")[0]))
    routes, far = build_routes(cities)
    src = block(src, "FLEET", "const FLEET = " + json.dumps(fleet, separators=(",", ":"), sort_keys=True) + ";")
    src = block(src, "ROUTES", "const ROUTES = " + json.dumps(routes, separators=(",", ":"), sort_keys=True) + ";\n  const FAR = "
                + json.dumps(far, separators=(",", ":"), sort_keys=True) + ";")
    with open(DEMO, "w", encoding="utf-8") as f:
        f.write(src)
    print("wrote {} airframes and {} callsigns into demo.js".format(sum(len(v) for t in fleet.values() for v in t.values()),
          sum(len(v) for p in routes.values() for v in p.values()) + sum(len(v) for p in far.values() for v in p.values())))


if __name__ == "__main__":
    main()
